### ISSUE TITLE
Failure during test

### ISSUE THREAD

**Issue by Aritra-Kundu** [sambit-giri/tools21cm#23]
Hi,

I am getting the following error in Smoothing.py while testing the installation. 

tests/test_BubbleStatistics.py ...                                       [ 12%]
tests/test_CosmoCalc.py .                                                [ 16%]
tests/test_IdentifyRegions.py ...                                        [ 28%]
tests/test_PointStatistics.py .....                                      [ 48%]
tests/test_PowerSpectrum.py .....                                        [ 68%]
tests/test_Smoothing.py ...F                                             [ 84%]
tests/test_Temperature.py ....                                           [100%]

=================================== FAILURES ===================================
____________________________ test_tophat_kernel_3d _____________________________

    def test_tophat_kernel_3d():
>   	kernel = t2c.tophat_kernel_3d(5)
E    TypeError: tophat_kernel_3d() missing 1 required positional argument: 'tophat_width'

tests/test_Smoothing.py:30: TypeError
=============================== warnings summary ===============================
tests/test_IdentifyRegions.py::test_bubbles_from_kmeans
tests/test_IdentifyRegions.py::test_bubbles_from_kmeans
  /home/aritra/anaconda3/envs/21cmTools/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:792: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 1.0 (renaming of 0.25).
    warnings.warn("'n_jobs' was deprecated in version 0.23 and will be"

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/test_Smoothing.py::test_tophat_kernel_3d - TypeError: tophat_ker...
=================== 1 failed, 24 passed, 2 warnings in 5.09s ===================

What could be the possible solution to this problem ?

**Comment by sambit-giri** [comment]
There was a missing parameter in the test. I have updated it.
It should be fine now.

**Comment by Aritra-Kundu** [comment]
Thanks!
