### ISSUE TITLE
Mistake in setup.py?

### ISSUE THREAD

**Issue by garrelt** [sambit-giri/tools21cm#24]
The setup.py file has 'git+https://github.com/sambit-giri/cosmospectra.git' in the list of requirements. This generates an error when I try to install it with pip 20.3.4. It seems this string should instead be 'cosmospectra @ git+https://github.com/sambit-giri/cosmospectra.git'.
See https://stackoverflow.com/questions/60414753/how-to-install-githttps-from-setup-py-using-install-requires

**Comment by sambit-giri** [comment]
Thank for the fix. I have implemented it now. Can you try to install it again directly using pip?

**Comment by sambit-giri** [comment]
Just to make a note about cosmospectra. It is a separate package that contains modules to calculate not only the power spectrum but also the higher-order statistics.

**Comment by garrelt** [comment]
The installation works with this change,
