### ISSUE TITLE
Incorrect critical frequency for effective area?

### ISSUE THREAD

**Issue by FurenDeng** [sambit-giri/tools21cm#56]
Hello,
In function sigma_noise_radio of telescope_functions.py, I notice you set
```python
	nu_crit = 1.1e5 						    # in kHz
	if nuso>nu_crit: ep = (nu_crit/nuso)**2
```
i.e. `nu_crit` is in kHz (which I guess is from [here](https://www.skao.int/sites/default/files/documents/d1-SKA-TEL-SKO-0000002_03_SKA1SystemBaselineDesignV2_1.pdf)).
However, instead of kHz
```python
	nuso  = 1420.0/(1.0 + z)
```
is is MHz and the unit seems like inconsistent.

**Comment by sambit-giri** [comment]
Thank you for noticing the inconsistency.
