### ISSUE TITLE
Bugs for unit in radio_telescope_layout.py?

### ISSUE THREAD

**Issue by FurenDeng** [sambit-giri/tools21cm#57]
In radio_telescope_layout.py, line 32-33 reads
```
    if isinstance(antll, u.quantity.Quantity):
        antll *= u.deg
```
I guess you want
```
    if not isinstance(antll, u.quantity.Quantity):
        antll *= u.deg
```
to attach unit.
BTW, I cannot understand line 76-77
```
    if isinstance(antxyz, u.quantity.Quantity):
        antxyz *= antxyz
```
which squares `antxyz`.

**Comment by sambit-giri** [comment]
Thank you for noticing these mistakes. The radio_telescope_layout.py is still under developement and, therefore, could have more bugs.
