### ISSUE TITLE
More efficient memory consumption in telescope_functions.py?

### ISSUE THREAD

**Issue by FurenDeng** [sambit-giri/tools21cm#58]
I notice that in line 148 of telescope_functions.py
```
    all_rotated_Nbase = np.array([earth_rotation_effect(Nbase, i, int_time, declination) for i in time_indices])
```
you create an array which contain all baselines for all time points which could be rather large. It seems like that making it a generator, i.e.
```
    all_rotated_Nbase =(earth_rotation_effect(Nbase, i, int_time, declination) for i in time_indices)
```
would be more efficient for memory usage because the baseline vectors would only be created when they are going to be used.
In following calculation you just loop over time indices and do not use the time dimension in a vectorized way. I cannot see the improvement on speed by making it an array.

**Comment by sambit-giri** [comment]
Thank you for this useful suggestion. I will update the script.
